services:
  web:
    build:
      context: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/activity_tracker
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=activity_tracker.settings
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: activity_tracker_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: minecraft
      POSTGRES_DB: activity_trackerdb
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network: