services:
  web:
    build:
      context: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/activity_tracker
    ports:
      - "8000:8000"
    env_file: 
      - .env
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: activity_tracker_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network: