# Generated by Django 5.1.3 on 2024-11-27 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('predefined_tag', models.CharField(choices=[('work', 'Work'), ('hobby', 'Hobby'), ('exercise', 'Exercise'), ('personal', 'Personal'), ('shopping', 'Shopping'), ('learning', 'Learning'), ('other', 'Other')], default='other', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['start_time'], name='activity_tr_start_t_286a63_idx'), models.Index(fields=['end_time'], name='activity_tr_end_tim_0c981c_idx')],
            },
        ),
    ]
