# Generated by Django 5.1.3 on 2024-11-28 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['predefined_tag'], name='activity_tr_predefi_d72160_idx'),
        ),
    ]
