# Generated by Django 5.1.3 on 2024-12-03 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_tracker', '0002_activity_activity_tr_predefi_d72160_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activity',
            name='activity_tr_predefi_d72160_idx',
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type'], name='activity_tr_activit_1c8a60_idx'),
        ),
    ]
