# Generated by Django 5.1.3 on 2025-05-03 20:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_tracker', '0002_activity_activity_tr_activit_1c8a60_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('bills', 'Bills'), ('shopping', 'Shopping'), ('other', 'Other')], default='other', max_length=20)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('description', models.TextField(blank=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='activity_tracker.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='activity_tr_user_id_7b3324_idx'), models.Index(fields=['date'], name='activity_tr_date_542042_idx'), models.Index(fields=['category'], name='activity_tr_categor_d77e1f_idx'), models.Index(fields=['year'], name='activity_tr_year_f55e4e_idx'), models.Index(fields=['month'], name='activity_tr_month_b77891_idx'), models.Index(fields=['activity'], name='activity_tr_activit_4d36f8_idx')],
            },
        ),
    ]
